[package]
name = "SUDOKU-SOLVER"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
board-em-api = "0.1.0"
sudoku-solver = "0.4.0"
array2d = "0.2.1"